#!/bin/bash

_cleanup() {
	[ -d "${tempDir}" ] && rm -r "${tempDir}" || :
}

trap _cleanup EXIT HUP INT QUIT ABRT ERR

set -e

myName=$(basename $(readlink -f $0))
baseDir=/srv/cups-pdf
#pdfDir="${baseDir}/pdf"
pdfName="${1}"
jpgDir="${baseDir}/jpg"
jpgName="${jpgDir}/$(basename "${pdfName}" .pdf).jpg"
jpgName="$(basename "${pdfName}" .pdf).jpg"
# Do not need to set the .jpg extension while using pdftocairo(1)
jpgName="$(basename "${pdfName}" .pdf)"
tempDir="$(mktemp -d -t "${myName}.XXX")"
# Permissions to set to resulting jpg. Anything acceptable by chmod(1)
jpgMode=0666
# SMB share to put results into (currently it must allow guests to write)
# Comment or set to empty to prevent SMB file transfer
smbShare=//scan/scan
logger="logger -i -s -t ${myName}"

# Uncomment two lines below to make it produce verbose logs
#set -x
#exec > /tmp/${myName}.$(date +%F.%s).log 2>&1
${logger} "Here I ($(id)) am"
${logger} "Options are $*"
[ -r "${pdfName}" ] || exit 1
${logger} "${pdfName} is readable, going on"
[ -d "${jpgDir}" ] || mkdir "${jpgDir}"
${logger} "${jpgDir} is here, going on"
# If pdf is multipaged there's gonna be more than one jpeg. In order to chmod
# them correctly do the conversion into a tempDir, chmod all the files in
# tempDir and move 'em into jpgDir
pushd "${tempDir}"
#convert "${pdfName}" -quality 100 "${jpgName}"
pdftocairo -jpeg -singlefile "${pdfName}" "${jpgName}"
${logger} "Converted ${pdfName} to ${jpgName}"
chmod ${jpgMode} *
${logger} "Chmodded * to ${jpgMode}"
cp -t "${jpgDir}" *
[ -n "${smbShare}" ] && find . -type f -print0 | tar -cT- --null | smbclient ${smbShare} "" -N -Tx -
${logger} "All done, exiting"
popd
