#!/bin/bash

_cleanup() {
	[ -d "${tempDir}" ] && rm -r "${tempDir}" || :
}

trap _cleanup EXIT HUP INT QUIT ABRT

set -e

myName=$(basename $(readlink -f $0))
baseDir=/srv/cups-pdf
#pdfDir="${baseDir}/pdf"
pdfName="${1}"
jpgDir="${baseDir}/jpg"
jpgName="${jpgDir}/$(basename "${pdfName}" .pdf).jpg"
jpgName="$(basename "${pdfName}" .pdf).jpg"
tempDir="$(mktemp -d -t "${myName}.XXX")"
# Permissions to set to resulting jpg. Anything acceptable by chmod(1)
jpgMode=0666
logger="logger -i -s -t ${myName}"

#exec > /tmp/${myName}.$(date +%F.%s).log 2>&1
${logger} "Here i ($(id)) am"
${logger} "Options are $*"
[ -r "${pdfName}" ] || exit 1
${logger} "${pdfName} is readable, going on"
[ -d "${jpgDir}" ] || mkdir "${jpgDir}"
${logger} "${jpgDir} is here, going on"
# If pdf is multipaged there's gonna be more than one jpeg. In order to chmod
# them correctly do the conversion into a tempDir, chmod all the files in
# tempDir and move 'em into jpgDir
pushd "${tempDir}"
convert "${pdfName}" "${jpgName}"
${logger} "Converted ${pdfName} to ${jpgName}"
chmod ${jpgMode} *
${logger} "Chmodded "*" to ${jpgMode}"
mv -t "${jpgDir}" *
${logger} "All done, exiting"
popd
